        PROGRAM HARD_DISK_MARKOV_CHAIN
        
        IMPLICIT NONE
C
C       *** DECLARATION DES VARIABLES ****
C 
        INTEGER :: NTRIALS, I, J, K, TEST, INTEGER
	REAL :: SQUAREDIM, RADIUS, DELTA
	REAL :: RAND1, RAND2, RAND3
	REAL, DIMENSION(4,2) :: COORD
C
C       *** INITIALISATION VARIABLE ***
C
	CALL RANDOM_SEED
	NTRIALS = 100
	I = 0
	J = 0
	K = 0
	TEST = 1
	SQUAREDIM = 10
	RADIUS = 1
	RAND1 = 0
	DELTA = 0
C
	COORD(1,:) = (/(SQUAREDIM-2*RADIUS)/4+RADIUS,
     $		       (SQUAREDIM-2*RADIUS)/4+RADIUS/)
	COORD(2,:) = (/3*(SQUAREDIM-2*RADIUS)/4+RADIUS,
     $		       3*(SQUAREDIM-2*RADIUS)/4+RADIUS/)
	COORD(3,:) = (/3*(SQUAREDIM-2*RADIUS)/4+RADIUS,
     $		       (SQUAREDIM-2*RADIUS)/4+RADIUS/)
	COORD(4,:) = (/(SQUAREDIM-2*RADIUS)/4+RADIUS,
     $		       3*(SQUAREDIM-2*RADIUS)/4+RADIUS/)
C
C       *** generer perturbation disque par disque***
C
	DO I=1,NTRIALS
	  CALL RANDOM_NUMBER(RAND1)
	  CALL RANDOM_NUMBER(RAND2)
	  CALL RANDOM_NUMBER(RAND3)
	  RAND1=(RAND1-0.5)*DELTA
	  RAND2=(RAND2-0.5)*DELTA
	  RAND3=RAND3**4+1
	  DO I=1,4
	  IF RAND3.NE.I THEN
	  DISTSQ=(COORD(I,1)-COORD(RAND3,1))**2+
     $           (COORD(I,2)-COORD(RAND3,2))**2
          END DO
	  COORD(FLOOR(RAND3),1)=COORD(FLOOR(RAND3),1)+RAND1
	  COORD(FLOOR(RAND3),2)=COORD(FLOOR(RAND3),2)+RAND2
	END DO
C
C
C
C
C	*** AFFICHAGE RESULTAT ***
C
C
	END PROGRAM
