        PROGRAM RANDOM_DISPLACEMENT
c
        IMPLICIT NONE
C
C       *** DECLARATION DES VARIABLES ****
C
        INTEGER              :: SITE, NMOVEMENTS, I, RANK
	REAL, DIMENSION(9,4) :: SPACE 
	REAL :: X, PROB
C
C       *** INITIALISATION VARIABLE ***
C
	NMOVEMENTS = 100000
	SITE = 9
	PROB = 0
C
	SPACE(1,:)=(/1,1,2,4/)
	SPACE(2,:)=(/1,2,3,5/)
	SPACE(3,:)=(/2,3,6,3/)
	SPACE(4,:)=(/4,1,7,5/)
	SPACE(5,:)=(/2,4,6,8/)
	SPACE(6,:)=(/3,5,6,9/)
	SPACE(7,:)=(/7,7,8,4/)
	SPACE(8,:)=(/7,9,8,5/)
	SPACE(9,:)=(/9,9,8,6/)
C
	CALL RANDOM_SEED
C
C       *** DEPLACEMENT DANS LA GRILLE ***
C
	DO I=1,NMOVEMENTS
	  CALL RANDOM_NUMBER(X)
	  X=(X*4)+1
c	  X=FLOOR(X)
	  RANK=X
c	  PRINT*, SITE, X, RANK
	  SITE = SPACE(SITE,RANK)
	  IF (SITE==1) THEN
	  PROB=PROB+1
	  ENDIF
	END DO
C
	PROB=PROB/NMOVEMENTS
	PRINT*, PROB
C

C
C	*** AFFICHAGE RESULTAT ***
C
C
	END PROGRAM
